### PR TITLE
v2.0.0rc1

### PR DESCRIPTION
**Pull request by znicholls**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by znicholls** [comment]
@conda-forge-admin, please rerender

**Comment by znicholls** [comment]
@rgieseke have I got the license update right?

**Comment by rgieseke** [comment]
In Pymagicc we went with AGPL-3 only

https://github.com/openscm/pymagicc/blob/master/pymagicc/__init__.py#L3

So i'd revert or undo that last commit, otherwise it looks fine to me!

The wording in the license file in Pymagicc is a bit confusing, but i understood it, that you have to explicitly state in your code that you use "or later".

We could consider that but keep it as AGPL3 for now.

**Comment by znicholls** [comment]
Beauty thanks. I think the old label got deprecated (https://spdx.org/licenses/) so have updated to make clear.

**Review by rgieseke — APPROVED** [review]

**Pull request merged**
